# Generated by Django 4.2.4 on 2023-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmt_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="attainable_speed",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="frame",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
