# Generated by Django 4.2.4 on 2023-08-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmt_api", "0002_alter_profile_attainable_speed_alter_profile_frame_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
