# Generated by Django 4.2.4 on 2023-08-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmt_api", "0003_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="attainable_speed",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dslam_hostname",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="frame",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pop_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="speed",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
