# Generated by Django 4.2.4 on 2023-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pmt_api", "0004_alter_profile_attainable_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="attainable_speed",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dslam_hostname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="frame",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="pop_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="speed",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
